apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: lgn10126v-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/lgn10126v-java-quarkus-gitops